-- Não existem dados fictícios nem utilizadores pré-criados.
-- O dataset real é importado por um utilizador autenticado através da Edge Function `import-leads`.
-- Ficheiro fonte incluído: supabase/imports/nikufra_leads.csv
